#███████╗██╗███╗   ███╗██████╗ ██╗     ███████╗███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗
#██╔════╝██║████╗ ████║██╔══██╗██║     ██╔════╝████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝
#███████╗██║██╔████╔██║██████╔╝██║     █████╗  ██╔████╔██║███████║██║  ███╗██║██║
#╚════██║██║██║╚██╔╝██║██╔═══╝ ██║     ██╔══╝  ██║╚██╔╝██║██╔══██║██║   ██║██║██║
#███████║██║██║ ╚═╝ ██║██║     ███████╗███████╗██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗
#╚══════╝╚═╝╚═╝     ╚═╝╚═╝     ╚══════╝╚══════╝╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝ ╚═════╝

#Created By Braiton

# wands:

#  fire_wand: > ID wand
#    material: BLAZE_ROD > Material name
#    name: "&cVarita de Fuego" > Name Wand item
#    lore: > Lore item
#      - "&7Una varita elemental."
#      - "&7Elemento: &cFuego"
#    cooldown: 3 > Number cooldown in seconds
#    xp-cost: 3 > Cost Xp in levels
#    powers: > List of powers
#      - fire
#      - ice
#      - lightning
#      - healing
#      - fire-beam
#      - lightning-beam
#      - ice-beam
#      - life-beam

wands:
  fire_wand:
    material: BLAZE_ROD
    name: "&cVarita de Fuego"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &cFuego"
    cooldown: 3
    xp-cost: 3
    powers:
      - fire

  ice_wand:
    material: STICK
    name: "&bVarita de Hielo"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &bHielo"
    cooldown: 3
    xp-cost: 3
    powers:
      - ice

  lightning_wand:
    material: BREEZE_ROD
    name: "&eVarita de Rayo"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &eRayo"
    cooldown: 3
    xp-cost: 3
    powers:
      - lightning

  healer_wand:
    material: GOLDEN_HOE
    name: "&aVarita de Curacion"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &aVida"
    cooldown: 8
    xp-cost: 4
    powers:
      - healing

  fire_beam_staff:
    material: BLAZE_ROD
    name: "&cVarita de Lanzallamas"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &cFuego"
    cooldown: 5
    xp-cost: 1
    powers:
      - fire-beam

  ice_beam_staff:
    material: STICK
    name: "&cVarita de Congelante"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &bHielo"
    cooldown: 5
    xp-cost: 1
    powers:
      - ice-beam

  lightning_beam_staff:
    material: BREEZE_ROD
    name: "&cVarita de Electrica"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &eRayo"
    cooldown: 6
    xp-cost: 2
    powers:
      - lightning-beam

  life_beam_staff:
    material: GOLDEN_HOE
    name: "&aVarita de Apoyo"
    lore:
      - "&7Una varita elemental."
      - "&7Elemento: &aVida"
    cooldown: 4
    xp-cost: 1
    powers:
      - life-beam